### ISSUE TITLE
2017 incompatiblity

### ISSUE THREAD

**Issue by Symbai** [mrlyceist/vstodolist#6]
It says it supports 2017 but I can't install it.

log:

01.2017 22:50:52 - Installiertes Produkt gefunden - Visual Studio Enterprise 2017 RC
19.01.2017 22:50:52 - VSIXInstaller.NoApplicableSKUsException: Diese Extension kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

**Comment by mrlyceist** [comment]
Honestly, I don't know, where is it said that ToDoList supports VS2017. It definitely not. But I'm working in this direction right now and I hope to release VS2017-compatible version by the end of February.

**Comment by Symbai** [comment]
It says that on the microsoft visual studio addin download page.
